 set version = "1.0.11" %}

package:
  name: libpll
  version: {{ version }}

build:
  number: 0

source:
  url: http://www.libpll.org/Downloads/libpll-{{ version }}.tar.gz 
  sha256: 1fb7af4d09bb935b0cc6c4d0ddff21a29ceff38c401328543d1639299ea31ec1

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
  host:
    - perl

test:
  commands : # make sure library was built and linked 
    - "otool -L $PREFIX/lib/libpll-sse3-pthreads.so | grep libm" # [osx]
    - "ldd $PREFIX/ldd/libpll-sse3-pthreads.so | grep libm"  # [not osx]

about:
  home: http://www.libpll.org/ 
  license: GPL
  license_file: COPYING
  summary: A highly optimized, parallized library to for phylogenetic inference.

extra:
  identifiers:
    - biotools:libpll
